default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: campaign_management_development

test:
  <<: *default
  database: campaign_management_test

production:
  <<: *default
  database: campaign_management_production
  username: campaign_management
  password: <%= ENV['CAMPAIGN_MANAGEMENT_DATABASE_PASSWORD'] %>
